version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fic
      POSTGRES_DB: amazon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
