version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: amazon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    ports:
      - "5432:5432"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
